[directory]
format = "[ ](#83a598)[ $path ]($style)"
style = "#83a598"

[character]
success_symbol = "[ ](#83a598)[ ➜](bold green)"
error_symbol = "[ ](#83a598)[ ➜](bold red)"

[cmd_duration]
format = "[󰔛 $duration]($style)"
style = "bg:none fg:#fabd2f"
show_notifications = false